### ISSUE TITLE
Serializers should be configurable (in initializer?)

### ISSUE THREAD

**Issue by fabn** [sorentwo/readthis#18]
As you moved to the binary format for flags and since the [hash is frozen](https://github.com/sorentwo/readthis/blob/bc1873be057aaddcf9bca2500227b2bc6165ee7c/lib/readthis/entity.rb#L13), no further serializers can be added anymore, e.g. `Oj`

The solution would be to allow user to add custom serializers (e.g. in a rails initializer file), something like
```ruby
Readthis.add_serializer(Oj)
```
Since having a frozen hash for serializer is a very good thing once the app is configured I'd also add a method to lock them, like 
```
Readthis.freeze_serializers!
```
The drawback is that user needs to call that method manually, in Rails code you might introduce a [railtie](http://api.rubyonrails.org/classes/Rails/Railtie.html) to freeze that hash after app initialization.

Also if you want to have some more slots you can refactor the binary flag to use 4 bytes for serializer I used only 3 bits because no user will use more than 3 or 4 of them, but you still have 4 bits available for whatever you need. Otherwise you can shift the compressed flag to the left side using `0x80` as value for `COMPRESSED_FLAG` in this way the 4 unused bits will remain in the center part of the byte.

Sorry to bother you with all these requests, but you're building a very good library and I'd like to use it in my projects.

**Comment by sorentwo** [comment]
I had very similar thoughts. I don't plan on releasing a new build until the ability to configure serializers has landed.

**Comment by sorentwo** [comment]
It is so! Closed with #21
