### ISSUE TITLE
Session store

### ISSUE THREAD

**Issue by espen** [sorentwo/readthis#33]
Is there any advantage for this project to have its own ActionDispatch session store over the ActionDispatch::Session::CacheStore?

If not, perhaps it should be mentioned in readme.md that it's possible to use this gem for storing sessions?

**Comment by sorentwo** [comment]
@espen Nope, there wouldn't be any advantage at all. The `CacheStore` only uses `read`, `write`, and `delete`, so there aren't any more advanced or optimized calls that would be made. I'd happily accept a PR that mentioned using it as a session store.

**Comment by espen** [comment]
For reference: one difference is that with most other cache stores you can add a prefix to the stored key. With CacheStore you can't add a prefix and it is namespaced with `_session_id ` in addition to the namespace defined in Readthis: https://github.com/rails/rails/blob/930110b0452bd33e0ee54e9ec6d68e904ba7a0ad/actionpack/lib/action_dispatch/middleware/session/cache_store.rb#L44

**Comment by sorentwo** [comment]
Can you give me an example of the cache keys you would like to see? The Rails CacheStore has a very small API and wouldn't take much, but I'd like to know exactly what you're aiming to achieve.

**Comment by espen** [comment]
I think the Rails Session CacheStore should handle this. I started a discussion here: https://groups.google.com/forum/#!topic/rubyonrails-core/kM7Bcrts3ME
