### ISSUE TITLE
Commands not supported by ActiveSupport::Cache::Store

### ISSUE THREAD

**Issue by espen** [sorentwo/readthis#34]
I want to expire a key and the `expire` command is not available in ActiveSupport::Cache::Store. In Dalli it's possible to use the Dalli client directly:  https://github.com/petergoldstein/dalli/blob/master/lib/active_support/cache/dalli_store.rb#L77. Would something similar be possible with readthis? Or how about adding additional methods like expire which is what redis-activesupport (redis-store) has done https://github.com/redis-store/redis-activesupport/blob/master/lib/active_support/cache/redis_store.rb#L190

**Comment by sorentwo** [comment]
You can run any command you like through the pool:

```ruby
Rails.cache.pool { |client| client.expire(key, seconds) }
```

**Comment by sorentwo** [comment]
@espen I've added a section to the README to outline how you can run arbitrary commands. Thanks for bringing this up.

**Comment by espen** [comment]
Awesome. Thanks for the quick answer.
