### ISSUE TITLE
Let us pass our own Connection Pool?

### ISSUE THREAD

**Issue by jeffblake** [sorentwo/readthis#39]
Hi,

I'm really looking forward to trying this out. Looking a bit at the source code, it looks like you don't allow for me to provide my own connection pool? To maintain predictable redis connection counts, I want to share my Sidekiq client pool with my session store and maybe my IdentityCache Pool as well. Would appreciate any insights here if you've benchmarked this. My plan:

- cache_store: Keep memcached for now. Cheaper for larger blobs (views)
- identity_cache_store: readthis (currently use memcached)
- session_store: readthis (currently use redis-store)

Thanks.

**Comment by sorentwo** [comment]
@jeffblake Hi, nice to hear you're considering using Readthis. It would be trivial to allow providing a connection pool when instantiating a new cache instance, so I'd be willing to make that change. Where I would push back is at the point of sharing a pool with Sidekiq. Sidekiq jobs are important and must be persisted, backed up to disk, and shouldn't be dropped with memory limitations. On the other hand, cache data can be ephemeral, doesn't require persistence, and should be evicted over time. I'd suggest using two different instances anyhow.

More information about that here http://sorentwo.com/2015/07/27/optimizing-redis-usage-for-caching.html.

**Comment by jeffblake** [comment]
That's a good point. In fact, I already have separate servers for session (redis, readthis) and worker (sidekiq) so I can't share pools anyway.
