### ISSUE TITLE
A word about delete_matched

### ISSUE THREAD

**Issue by dreyks** [sorentwo/readthis#48]
As stated in the Readme the `delete_matched` is an O(n) operation. However this is what sometimes really is needed, regardless of the performance hit.
`redis-activesupport` gem provides this api with a [warning](https://github.com/redis-store/redis-activesupport/blob/668a0fc6192a3c7a6dad7e2fd3a8740ccfd2dacd/lib/active_support/cache/redis_store.rb#L66) in the documentation. After all this is [providing sharp knives](https://m.signalvnoise.com/provide-sharp-knives-cc0a22bf7934#.6057518yo), isn't it?

Would you mind adding a `delete_matched` method anyway?

**Comment by sorentwo** [comment]
@dreyks Thanks for prompting me to look at this again. As it happens I have a need for `delete_matched` currently as well, but on a database that is large enough where using `KEYS` wasn't an option.

Please try out `delete_matched` on the master branch and let me know how it works for you. You can find [documentation on rubydoc.info](http://www.rubydoc.info/github/sorentwo/readthis/master/Readthis/Cache#delete_matched-instance_method).
