### ISSUE TITLE
does not work with rails5 cached collection renderer

### ISSUE THREAD

**Issue by dreyks** [sorentwo/readthis#49]
So, Rails5 introduced multi fetching when rendering a collection in partial. It does not use `fetch_multi` but calls directly `read_multi` instead, thus treating `nil` values as a valid cached contents. This leads to such partials being considered as "present" in cache and just being `nil`

As seen [here](https://github.com/rails/rails/blob/7714e83da0c8062658a8f38470c1163532f19552/actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb#L17) the hits are counted as a size of result returned by `multi_read`. Later to check if there's a hit for a particular partial it [calls](https://github.com/rails/rails/blob/7714e83da0c8062658a8f38470c1163532f19552/actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb#L47) fetch on the result hash.

Abstract [`ActiveSupport::Cache::Store#read_multi`](https://github.com/rails/rails/blob/7714e83da0c8062658a8f38470c1163532f19552/activesupport/lib/active_support/cache.rb#L349) treats `nil` as cache miss

To make `readthis` a drop-in replacement you'll sadly have to make a backwards-incompatible change to `read_multi`

**Comment by sorentwo** [comment]
Interestingly I've always been in favor of treating `nil` as a cache miss, so I'm fine with the change.

**Comment by sorentwo** [comment]
On second thought, or at least, on attempt, this is a little trickier. `fetch_multi` relies on the fact that `read_multi` retains `nil` values, so this will take some more refactoring.

**Comment by dreyks** [comment]
yes you'll have to remove missed keys from read_multi and this will probably break some things

**Comment by sorentwo** [comment]
2.0.0 has been released with the breaking change, and an escape hatch to retain the old behavior: c9c5c0a
