### ISSUE TITLE
How to close redis connection?

### ISSUE THREAD

**Issue by nicozhang** [sorentwo/readthis#62]
I use Readthis::Cache.new to get a  client, but i can not find a way to close this redis connection. So I meet a very serious problem of redis,  max number of clients reached.

**Comment by sorentwo** [comment]
All of the redis connections are stored in a [connection pool](https://github.com/mperham/connection_pool). You can technically close connections by [shutting down the pool](https://github.com/mperham/connection_pool#shutdown), but that will leave the cache in a bad state.

The default pool size is 5, so you'll get at most 5 connections if you have enough parallel traffic. If you have very low connection limits you can configure a smaller pool size using the `pool_size` option:

`Readthis::Cache.new(pool_size: 2)`
