### ISSUE TITLE
Is there any support for distributed client for redis?

### ISSUE THREAD

**Issue by OPhamster** [sorentwo/readthis#63]
Couldn't find the code for distributed client for redis. Does readthis support reads and writes to a distributed redis cluster?

**Comment by sorentwo** [comment]
Readthis doesn't have built in support for Redis Cluster. There isn't an official ruby library for cluster, so the usual workaround is a custom redis cluster proxy.

Readthis relies on `MULTI` calls in a lot of places, but `MULTI` falls apart when reading data from a cluster. Other libraries have a switch to choose `PIPELINE` over `MULTI` in this situation, but we don't have support for that currently.
