### ISSUE TITLE
Usage with Puma and connection_pool

### ISSUE THREAD

**Issue by ViTVetal** [sorentwo/readthis#65]
Hello!
I want to use readthis_store on multithreading Puma. I use Redis in application and for the cache. I use [connection_pool](https://github.com/mperham/connection_pool) 
[more](https://stackoverflow.com/a/28283255/3194048)

```
#initializers/redis.rb

require 'connection_pool'

REDIS = ConnectionPool.new(size: 10) { Redis.new db: 15, driver: :hiredis }



#Somewhere in the app

REDIS.with do |conn|
  conn.geoadd($DRIVER_LOCATIONS, latitude, longitude, id)
end
```
```
development.rb

config.cache_store = :readthis_store, { 
  expires_in: 1.minutes.to_i,
  namespace: 'cache',
  redis: { url: 'redis://localhost:6379/1', driver: :hiredis }
}
```

Should I use same connection pool for cache and if yes how can I do it?

**Comment by sorentwo** [comment]
Readthis already uses `connection_pool` to manage a pool of redis connections. You can access to the pool directly, as [documented in the README](https://github.com/sorentwo/readthis#running-arbitrary-redis-commands):

```ruby
Rails.cache.pool.with do |conn|
  conn.geoadd($DRIVER_LOCATIONS, latitude, longitude, id)
end
```

You can configure the `pool_size` and the `pool_timeout` directly in your `cache_store` setup:

```ruby
config.cache_store = :readthis_store, { 
  expires_in: 1.minutes.to_i,
  namespace: 'cache',
  pool_size: 10,
  redis: { url: 'redis://localhost:6379/15', driver: :hiredis }
}
```

**Comment by ViTVetal** [comment]
So there is no matter that I also use Redis in application for non cache related things (`geoadd` etc) and Redis will use same db for cache and for other things (as you can see for pool I used db №15 and for cache №1). Right?

**Comment by sorentwo** [comment]
No, so long as all of the data is ephemeral there isn't any problem with doing that. I've written about this a bit in the past: https://sorentwo.com/2015/07/27/optimizing-redis-usage-for-caching.html
