### ISSUE TITLE
Using readthis as ActiveRecord::Cache::Store with hiredis

### ISSUE THREAD

**Issue by Nekromancer** [sorentwo/readthis#7]
Hi
I'd love to use redis as cache with hiredis driver, but i'm not sure how to use it here.

Would this work?

```ruby
config.cache_store = :readthis_store, ENV.fetch('REDIS_URL'), {
  expires_in: 60.minutes,
  namespace: 'cache',
  driver: :hiredis
}
```

**Comment by dblandin** [comment]
Hey @Nekromancer,

The latest released version of Readthis, `v0.6.2`, is [preconfigured to use hiredis](https://github.com/sorentwo/readthis/blob/9aa15cec5ce27e5e333278bb5ea3a351c8ecd1d1/lib/readthis/cache.rb#L53-L55) and specifies the [hiredis gem](https://rubygems.org/gems/hiredis) as a dependency so Bundler should install it alongside the `readthis` gem.

On master and in the next released version of Readthis, `v0.7.0`, you may [specify another driver](https://github.com/sorentwo/readthis/blob/f2bf22550958ad0232d6537e3029127c8339a82f/lib/readthis/cache.rb#L52-L54) via the `driver` configuration option, just as you have shown above. Based on what I see on the master branch now, Readthis will default to `:hiredis` but you'll have to explicitly include the [hiredis gem](https://rubygems.org/gems/hiredis) to your project's `Gemfile`.

**Comment by Nekromancer** [comment]
That's great, thanks for help ;)

**Comment by dblandin** [comment]
@Nekromancer No problem!

Thanks for the issue and let us know if you have any other questions. :+1:
