### ISSUE TITLE
Gem is incompatible with MRI Ruby 2.0.0p247

### ISSUE THREAD

**Issue by vovayartsev** [sorentwo/readthis#8]
Because of this line in the sources, it fails to run on MRI Ruby 2.0.0p247
`Object.const_defined?('ActiveSupport::Notifications')`

The exception is:
<pre>NameError: wrong constant name ActiveSupport::Notifications</pre>

**Comment by sorentwo** [comment]
@vovayartsev: Thanks for the report. I swapped out the use of `const_defined?` for plain `defined?`, so it should be all good.
